"""add new fields to testplan table

Revision ID: 0232af89acc2
Revises: 
Create Date: 2025-12-19 13:46:26.736520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0232af89acc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('config_key'), table_name='configurations')
    op.drop_index(op.f('idx_category'), table_name='configurations')
    op.drop_table('configurations')
    op.drop_index(op.f('idx_created_at'), table_name='modbus_logs')
    op.drop_index(op.f('idx_status'), table_name='modbus_logs')
    op.drop_table('modbus_logs')
    op.drop_index(op.f('idx_project_code'), table_name='projects')
    op.drop_index(op.f('project_code'), table_name='projects')
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.add_column('sfc_logs', sa.Column('test_session_id', sa.Integer(), nullable=False))
    op.add_column('sfc_logs', sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('sfc_logs', sa.Column('command', sa.String(length=255), nullable=True))
    op.add_column('sfc_logs', sa.Column('response', sa.Text(), nullable=True))
    op.alter_column('sfc_logs', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sfc_logs', 'status',
               existing_type=mysql.ENUM('SUCCESS', 'FAILED', 'TIMEOUT', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_index(op.f('idx_created_at'), table_name='sfc_logs')
    op.drop_index(op.f('idx_session'), table_name='sfc_logs')
    op.drop_index(op.f('idx_status'), table_name='sfc_logs')
    op.create_index(op.f('ix_sfc_logs_id'), 'sfc_logs', ['id'], unique=False)
    op.drop_constraint(op.f('sfc_logs_ibfk_1'), 'sfc_logs', type_='foreignkey')
    op.create_foreign_key(None, 'sfc_logs', 'test_sessions', ['test_session_id'], ['id'])
    op.drop_column('sfc_logs', 'operation')
    op.drop_column('sfc_logs', 'error_message')
    op.drop_column('sfc_logs', 'request_data')
    op.drop_column('sfc_logs', 'response_data')
    op.drop_column('sfc_logs', 'session_id')
    op.drop_index(op.f('idx_station_code'), table_name='stations')
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_station_code'), 'stations', ['station_code'], unique=False)
    op.add_column('test_plans', sa.Column('item_key', sa.String(length=50), nullable=True, comment='ItemKey - 項目鍵值'))
    op.add_column('test_plans', sa.Column('value_type', sa.String(length=50), nullable=True, comment='ValueType - 數值類型'))
    op.add_column('test_plans', sa.Column('limit_type', sa.String(length=50), nullable=True, comment='LimitType - 限制類型'))
    op.add_column('test_plans', sa.Column('eq_limit', sa.String(length=100), nullable=True, comment='EqLimit - 等於限制'))
    op.add_column('test_plans', sa.Column('pass_or_fail', sa.String(length=20), nullable=True, comment='PassOrFail - 通過或失敗'))
    op.add_column('test_plans', sa.Column('measure_value', sa.String(length=100), nullable=True, comment='measureValue - 測量值'))
    op.add_column('test_plans', sa.Column('execute_name', sa.String(length=100), nullable=True, comment='ExecuteName - 執行名稱'))
    op.add_column('test_plans', sa.Column('case_type', sa.String(length=50), nullable=True, comment='case - 案例類型'))
    op.add_column('test_plans', sa.Column('command', sa.String(length=500), nullable=True, comment='Command - 命令'))
    op.add_column('test_plans', sa.Column('timeout', sa.Integer(), nullable=True, comment='Timeout - 超時時間(毫秒)'))
    op.add_column('test_plans', sa.Column('use_result', sa.String(length=100), nullable=True, comment='UseResult - 使用結果'))
    op.add_column('test_plans', sa.Column('wait_msec', sa.Integer(), nullable=True, comment='WaitmSec - 等待毫秒'))
    op.drop_index(op.f('idx_station_sequence'), table_name='test_plans')
    op.create_index(op.f('ix_test_plans_id'), 'test_plans', ['id'], unique=False)
    op.drop_index(op.f('idx_result'), table_name='test_results')
    op.drop_index(op.f('idx_session'), table_name='test_results')
    op.drop_index(op.f('idx_test_time'), table_name='test_results')
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.create_index(op.f('ix_test_results_result'), 'test_results', ['result'], unique=False)
    op.create_index(op.f('ix_test_results_session_id'), 'test_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_time'), 'test_results', ['test_time'], unique=False)
    op.drop_index(op.f('idx_result'), table_name='test_sessions')
    op.drop_index(op.f('idx_serial_number'), table_name='test_sessions')
    op.drop_index(op.f('idx_station_time'), table_name='test_sessions')
    op.create_index(op.f('ix_test_sessions_id'), 'test_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_test_sessions_serial_number'), 'test_sessions', ['serial_number'], unique=False)
    op.drop_index(op.f('idx_role'), table_name='users')
    op.drop_index(op.f('idx_username'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('idx_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_role'), 'users', ['role'], unique=False)
    op.drop_index(op.f('ix_test_sessions_serial_number'), table_name='test_sessions')
    op.drop_index(op.f('ix_test_sessions_id'), table_name='test_sessions')
    op.create_index(op.f('idx_station_time'), 'test_sessions', ['station_id', 'start_time'], unique=False)
    op.create_index(op.f('idx_serial_number'), 'test_sessions', ['serial_number'], unique=False)
    op.create_index(op.f('idx_result'), 'test_sessions', ['final_result'], unique=False)
    op.drop_index(op.f('ix_test_results_test_time'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_session_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_result'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.create_index(op.f('idx_test_time'), 'test_results', ['test_time'], unique=False)
    op.create_index(op.f('idx_session'), 'test_results', ['session_id'], unique=False)
    op.create_index(op.f('idx_result'), 'test_results', ['result'], unique=False)
    op.drop_index(op.f('ix_test_plans_id'), table_name='test_plans')
    op.create_index(op.f('idx_station_sequence'), 'test_plans', ['station_id', 'sequence_order'], unique=False)
    op.drop_column('test_plans', 'wait_msec')
    op.drop_column('test_plans', 'use_result')
    op.drop_column('test_plans', 'timeout')
    op.drop_column('test_plans', 'command')
    op.drop_column('test_plans', 'case_type')
    op.drop_column('test_plans', 'execute_name')
    op.drop_column('test_plans', 'measure_value')
    op.drop_column('test_plans', 'pass_or_fail')
    op.drop_column('test_plans', 'eq_limit')
    op.drop_column('test_plans', 'limit_type')
    op.drop_column('test_plans', 'value_type')
    op.drop_column('test_plans', 'item_key')
    op.drop_index(op.f('ix_stations_station_code'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.create_index(op.f('idx_station_code'), 'stations', ['station_code'], unique=False)
    op.add_column('sfc_logs', sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sfc_logs', sa.Column('response_data', mysql.JSON(), nullable=True))
    op.add_column('sfc_logs', sa.Column('request_data', mysql.JSON(), nullable=True))
    op.add_column('sfc_logs', sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.add_column('sfc_logs', sa.Column('operation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.drop_constraint(None, 'sfc_logs', type_='foreignkey')
    op.create_foreign_key(op.f('sfc_logs_ibfk_1'), 'sfc_logs', 'test_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sfc_logs_id'), table_name='sfc_logs')
    op.create_index(op.f('idx_status'), 'sfc_logs', ['status'], unique=False)
    op.create_index(op.f('idx_session'), 'sfc_logs', ['session_id'], unique=False)
    op.create_index(op.f('idx_created_at'), 'sfc_logs', ['created_at'], unique=False)
    op.alter_column('sfc_logs', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('SUCCESS', 'FAILED', 'TIMEOUT', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('sfc_logs', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('sfc_logs', 'response')
    op.drop_column('sfc_logs', 'command')
    op.drop_column('sfc_logs', 'timestamp')
    op.drop_column('sfc_logs', 'test_session_id')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.create_index(op.f('project_code'), 'projects', ['project_code'], unique=True)
    op.create_index(op.f('idx_project_code'), 'projects', ['project_code'], unique=False)
    op.create_table('modbus_logs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('register_address', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operation', mysql.ENUM('READ', 'WRITE'), nullable=False),
    sa.Column('value', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('status', mysql.ENUM('SUCCESS', 'FAILED'), nullable=False),
    sa.Column('error_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_status'), 'modbus_logs', ['status'], unique=False)
    op.create_index(op.f('idx_created_at'), 'modbus_logs', ['created_at'], unique=False)
    op.create_table('configurations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('config_value', mysql.JSON(), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('is_system', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_category'), 'configurations', ['category'], unique=False)
    op.create_index(op.f('config_key'), 'configurations', ['config_key'], unique=True)
    # ### end Alembic commands ###
